### ISSUE TITLE
Doesn't work with ngModel

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-dropdowns#1]
Hi,

[(ngModel)]="value" or [(value)]="value"

can set the value but does not get the value!

Regards

j.nord

**Comment by PrasanthPalani** [comment]
Hi J-nord

Sorry for the inconvenience.

Query: Doesn't work with ngModel.

We have validated your query. We are unable to reproduce the reported issue on our end. The value property working properly with ngModel. For your convenience, we have prepared simple ng sample with DropDownList component. Please get that sample in the below GitHub location.

Sample location: [ej2-ng-DropDownList-ngMode](https://github.com/SyncfusionSamples/ej2-dropdownlist-ngModel)

This sample works as ng two-way binding support. In this sample, initially, we have selected a game through value property.

`<ej-dropdownlist id='ddlelement' [dataSource]='data' [(value)]='selectedGame' placeholder='Select a game'></ej-dropdownlist>
public selectedGame: string = 'Badminton';`

Then the corresponding selected item's text updated in input element using ngModal.

`<ej-dropdownlist id='ddlelement' [dataSource]='data' [(value)] ='selectedGame' placeholder='Select a game'></ej-dropdownlist>
   <input type='text' [(ngModel)] ='selectedGame' style='width:245px; height:25px'/>
`

If we have misunderstood your query or still you face any difficulties, kindly revert the provided sample based on your application along with the replication procedure to reproduce the issue at our end. This would be more helpful for us to provide a solution at the earliest.

Thanks,
Prasanth P

**Comment by j-nord** [comment]
Hi Prasnth,

we have the Dropdown box in a Anuglar custom control:

```
//get accessor
    get value(): any {
        return this.innerValue;
    };


 //set accessor including call the onchange callback
    set value(v: any) {
        if (v) {
            if (v !== this.innerValue) {
                this.innerValue = v;
                this.onChangeCallback(v);
                this.change.emit(v);                    // Change Event fired by change
            }
        }
    }

the get accessor doesn't work with dropdown ej2 with ej1 it works

Regards

j.nord

**Comment by PrasanthPalani** [comment]
Hi j-nord

Sorry for the inconvenience.

We have validated your query. In ej2 DropDownList component’s value property working properly with ngModel (get and set). We couldn’t get your requirement clearly.  Kindly provide the sample
based on your application along with the replication procedure to reproduce the issue at our end. This would be more helpful for us to provide an appropriate solution at the earliest.

Please let us know if you have any other concern, we will happy to help you.

Thanks,
Prasanth P

**Comment by j-nord** [comment]
Hi Prasanth,

we have found the issue. It is only possible to work with string values. "number" values doesn't work.

Regards

j.nord

**Comment by rajendranr-5483** [comment]
@j-nord, 

We have validated your query, we suspect that issue may raise due to type mismatch for elements. For two-way binding support, when the dropdownlist value is in number type, then the corresponding input element type also in number. For your convenience, we have prepared DropDownList angular two-way binding sample in Plunker. Please get that sample in the below link,

Sample: [EJ2-ng-DropDownList-value-binding](http://plnkr.co/edit/Puiohtnal7KMhTpqUuls?p=preview)

In this sample, the input element type is number. When we change the value in input element, then the corresponding text will be updated in DropDownList.

Regards,
Rajendran R

**Comment by j-nord** [comment]
Thanks,

we only have found one way: 

we convert the numeric value into string. Also the datasource. Then it works.

Regards

j.nord

**Comment by saravanangn** [comment]
@j-nord ,
We have checked the reported issue by binding a number value to DropDownList through ngModel with custom component. The number value is set/get properly at our end. 

- Could you please ensure whether input element has “number” type in your application? 

We have prepared the below sample to meet your requirement.
https://stackblitz.com/edit/angular-qxhsm1  

Please find the code snippet of value binding through ngModel, that we have used in sample.

```
@Component({
  selector: 'custom-input',
  template: ' <form #f="ngForm" novalidate>
      <input name="first" type="number" [(ngModel)]="Value"/>
      <ejs-dropdownlist name="ddl" id='games' [dataSource]='sportsData' [fields]='fields' [(value)]='Value' [placeholder]='waterMark'  [popupHeight]='height'></ejs-dropdownlist>   
    </form> '
})
```
Please look the sample and let us know whether it met your requirement. If issue persists, kindly revert by modifying the above sample to reproduce the issue at our side.

Regards,
Saravanan G
