### ISSUE TITLE
Refresh datasource at runtime and set index after refresh doesn't work

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-dropdowns#3]
Hi,

we refresh the datasource at runtime for the dropdown box and after the refresh we set the index to 0. But the dropdown-box not display the first text value. We test all possibilities with timeout and set the value again but the dropdown-box display nothing.

Regards
j.nord

**Comment by Gopigovin** [comment]
Hi @j-nord , 

Thanks for using Syncfusion EJ2 components.

We have analyzed your requirement. Here dataSource and index properties passed at a time for changes, so in our source we will compare the previous and current passing value, if it same we skip the corresponding property changes. Here index property have same ‘0’ value, so index value not affect. 

To achieve your requirement using [dataBind()](http://ej2.syncfusion.com/15.4.17/documentation/base/api-component.html?lang=typescript#databind) public method for immediate change of dataSource property and then change the index value like below code . Please refer the below code snippet where to use the dataBind method.

```
[app.component.ts]

// DropDownList dataSource change at run time
onclick() {
    let sportsData1: { [key: string]: Object }[] = [
        { code: 'item1', Vegetable: 'Cabbage' },
        { code: 'item2', Vegetable: 'Spinach' },
        { code: 'item3', Vegetable: 'Wheat grass' }
    ];
    this.ddlObj.fields = { text: 'Vegetable', value: 'code' };
    this.ddlObj.dataSource = sportsData1;
    this.ddlObj.dataBind();  // Update the dataSource and fields properties alone on this line.

    this.ddlObj.index = 0; // Update the index property alone on this line

  } 
}

```
For your convenience, we are prepared the simple plunker sample. 

Sample Link: http://plnkr.co/edit/tGOWMsemhn2Fu1rB6gwh?p=preview 

Please let us know, if you have any other concern, we will happy to assist you.

Regards,
Gopi G.
