### ISSUE TITLE
Dropdown on modal

### ISSUE THREAD

**Issue by LastCodeDE** [syncfusion/ej2-ng-dropdowns#5]
Hello,

the selection list does not open directly below or above the combo box.

This problem is happens when the site has a long content and we have to scroll down to press a button to open the modal screen. 

The dropdown is on a modal screen on the site. 

For example:
(See attachement)
![dropdown](https://user-images.githubusercontent.com/15675686/34992146-7b6f3836-facc-11e7-9825-c469d6d0add0.png)

The Modal is from
https://ng-bootstrap.github.io/#/components/modal/examples

Regards

**Comment by Gopigovin** [comment]
Hi SireCode,


Thanks for patience.


We have confirmed that the issue with (“ **popup does not open directly** ”) is a defect and we have logged a defect report. The fix will be rollout on upcoming patch release 30th Jan 2018.


Please let us know if you have any concern, we will happy to assist you.


Regards,
Gopi G.

**Comment by Gopigovin** [comment]
Hi SireCode,  

Thanks for patience.  

We are fixed you reported issue (**popup does not open directly**) and rolled out in  v15.4.27-preview release. Now, you can upgrade the ej2-dropdowns npm package on your application.  

NPM package: https://www.npmjs.com/package/@syncfusion/ej2-ng-dropdowns  

Please let us know, if you have any other concern, we will happy to assist you.   

Regards,  
Gopi G.
